---

services:
    web:
        image: bearstech/nginx
        volumes:
          - ./nginx.conf:/etc/nginx/sites-enabled/default:ro
          - ./www:/var/www/html:ro
        depends_on:
            - gitlab-log-reader

    gitlab-log-reader:
        image: gitlab-log-reader
        command: /usr/local/bin/log-reader-ip /var/log/gitlab/production_json.log
        volumes:
            - ./log/:/var/log/gitlab/:ro
        depends_on:
            - logger

    logger:
        image: gitlab-log-reader-mockup
        environment:
            LOG_PATH: /var/log/gitlab/production_json.log
        volumes:
            - ./log/:/var/log/gitlab/

    client_white:
        image: bearstech/debian:11
        command: curl -v logger:5000

    client_web:
        image: bearstech/debian:11
        command: curl -vL web:8000/
